export type SoundId =
  | 'launch'
  | 'breakWood'
  | 'breakBrick'
  | 'breakIron'
  | 'breakGold'
  | 'breakBoost'
  | 'critical'
  | 'stopWood'
  | 'stopBrick'
  | 'stopIron'
  | 'newBest'
  | 'rushStart'
  | 'buy'
  | 'denied'
  | 'tap'
  | 'pick';
