import { DroppedItem } from '../entities/DroppedItem';import { impactParticles,updateParticles,type Particle } from '../effects/Particles';import { AudioEngine } from '../effects/AudioEngine';import type { GameStore } from '../systems/GameStore';
export class HomeScene { root=document.createElement('section');private canvas=document.createElement('canvas');private ctx=this.canvas.getContext('2d')!;private drops:DroppedItem[]=[];private particles:Particle[]=[];private audio=new AudioEngine();private last=performance.now();private shake=0;private flash=0;private frame=0;private resize?:ResizeObserver;
 constructor(private store:GameStore){this.root.className='scene home-scene';this.root.innerHTML=`<header class="scene-header"><div><span class="eyebrow">FIELD SITE 01</span><h1>赤土の採掘場</h1></div><div class="currency"><span>調査資金</span><strong data-coins>0</strong></div></header><div class="progress-card"><div><span data-rock-subtitle></span><strong data-rock-name></strong></div><span data-rock-count></span></div><div class="mine-stage"><canvas aria-label="採掘場。岩や落ちた発見物をタップできます"></canvas><div class="hp-panel"><div class="hp-label"><b>岩の耐久度</b><span data-hp></span></div><div class="hp-track"><i data-hpbar></i></div></div><div class="drop-hint">落ちた発見物をタップして回収</div><button class="mine-button" type="button"><span class="tool-mark">⚒</span><span><b>岩を叩く</b><small data-power></small></span></button></div><div class="toast" role="status"></div>`;this.root.querySelector('.mine-stage')!.prepend(this.canvas);this.root.querySelector('.mine-button')!.addEventListener('click',()=>this.hitRock());this.canvas.addEventListener('pointerdown',e=>this.pointer(e));this.resize=new ResizeObserver(()=>this.size());this.resize.observe(this.canvas.parentElement!);this.store.addEventListener('changed',()=>this.renderHud());this.audio.enabled=this.store.state.settings.sound;this.renderHud();this.size();this.frame=requestAnimationFrame(t=>this.loop(t))}
 destroy(){cancelAnimationFrame(this.frame);this.resize?.disconnect()}
 private size(){const box=this.canvas.parentElement!.getBoundingClientRect();const dpr=Math.min(devicePixelRatio,2);this.canvas.width=box.width*dpr;this.canvas.height=box.height*dpr;this.canvas.style.width=`${box.width}px`;this.canvas.style.height=`${box.height}px`;this.ctx.setTransform(dpr,0,0,dpr,0,0)}
 private hitRock(){const result=this.store.hit();this.audio.hit();if(result.broken)this.audio.break();if(this.store.state.settings.haptics)navigator.vibrate?.(result.broken?[28,35,35]:12);const w=this.canvas.clientWidth,h=this.canvas.clientHeight,x=w/2,y=h*.42;this.shake=result.broken?9:4;this.flash=.1;this.particles.push(...impactParticles(x+(Math.random()-.5)*80,y,this.store.rock.color,result.broken?18:7));result.drops.forEach((item,i)=>setTimeout(()=>this.drops.push(new DroppedItem(item,x,y,250)),i*120));this.canvas.classList.remove('impact');void this.canvas.offsetWidth;this.canvas.classList.add('impact')}
 private pointer(e:PointerEvent){const r=this.canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;for(let i=this.drops.length-1;i>=0;i--){const drop=this.drops[i]!;if(drop.hit(x,y)){this.drops.splice(i,1);this.store.collect(drop.item.id);this.audio.collect();this.showToast(`${drop.item.glyph} ${drop.item.name} を回収`);return}}const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(Math.hypot(x-w/2,y-h*.42)<115)this.hitRock()}
 private showToast(text:string){const el=this.root.querySelector('.toast')!;el.textContent=text;el.classList.remove('show');void(el as HTMLElement).offsetWidth;el.classList.add('show')}
 private renderHud(){const s=this.store.state,r=this.store.rock;this.set('[data-coins]',`${s.coins} c`);this.set('[data-rock-name]',r.name);this.set('[data-rock-subtitle]',r.subtitle);this.set('[data-rock-count]',`${s.rocksBroken} 岩石を調査済み`);this.set('[data-hp]',`${s.rockHp} / ${r.maxHp}`);this.set('[data-power]',`採掘力 ${this.store.damage}`);(this.root.querySelector('[data-hpbar]') as HTMLElement).style.width=`${s.rockHp/r.maxHp*100}%`}
 private set(sel:string,text:string){const el=this.root.querySelector(sel);if(el)el.textContent=text}
 private loop(now:number){const dt=Math.min((now-this.last)/1000,.034);this.last=now;this.draw(dt);this.frame=requestAnimationFrame(t=>this.loop(t))}
 private draw(dt:number){const c=this.ctx,w=this.canvas.clientWidth,h=this.canvas.clientHeight,ground=h*.78;c.clearRect(0,0,w,h);c.save();if(this.shake>0){c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);this.shake=Math.max(0,this.shake-35*dt)}c.fillStyle='#332b24';c.fillRect(0,ground,w,h-ground);c.fillStyle='#49392c';for(let i=0;i<12;i++)c.fillRect((i*67)%w,ground+8+(i%3)*9,20,2);const x=w/2,y=h*.42;c.save();c.translate(x,y);if(this.flash>0){c.scale(.97,1.03);this.flash-=dt}const rock=this.store.rock;c.fillStyle=rock.shadow;c.beginPath();c.ellipse(8,87,112,22,0,0,Math.PI*2);c.fill();c.fillStyle=rock.color;c.beginPath();c.moveTo(-105,55);c.lineTo(-85,-42);c.lineTo(-35,-92);c.lineTo(48,-83);c.lineTo(102,-28);c.lineTo(94,58);c.lineTo(43,86);c.lineTo(-48,83);c.closePath();c.fill();c.strokeStyle='#4b4038';c.lineWidth=5;c.stroke();c.fillStyle='rgba(255,255,255,.08)';c.beginPath();c.moveTo(-74,-34);c.lineTo(-30,-72);c.lineTo(2,-61);c.lineTo(-18,-12);c.closePath();c.fill();c.strokeStyle='#443b35';c.lineWidth=3;c.beginPath();c.moveTo(20,-58);c.lineTo(5,-10);c.lineTo(36,9);c.lineTo(18,45);c.moveTo(-45,5);c.lineTo(-20,24);c.lineTo(-31,61);c.stroke();c.restore();this.drops.forEach(d=>{d.update(dt,ground);c.save();c.translate(d.x,d.y);c.rotate(d.rotation);c.shadowColor='rgba(0,0,0,.45)';c.shadowBlur=8;c.shadowOffsetY=5;c.fillStyle=d.item.color;c.beginPath();c.roundRect(-23,-23,46,46,12);c.fill();c.shadowColor='transparent';c.strokeStyle='#ead8b4';c.lineWidth=2;c.stroke();c.fillStyle='#251f1a';c.font='bold 22px serif';c.textAlign='center';c.textBaseline='middle';c.fillText(d.item.glyph,0,1);c.restore()});this.particles=updateParticles(this.particles,dt);this.particles.forEach(p=>{c.globalAlpha=Math.min(1,p.life*3);c.fillStyle=p.color;c.fillRect(p.x,p.y,p.size,p.size)});c.globalAlpha=1;c.restore()}
}
