import { DroppedItem } from '../entities/DroppedItem';
import { drawItem } from '../entities/ItemRenderer';
import { RockRenderer } from '../entities/RockRenderer';
import { impactParticles, updateParticles, type Particle } from '../effects/Particles';
import { AudioEngine } from '../effects/AudioEngine';
import { UPGRADES, itemById, upgradeCost } from '../data/content';
import type { GameStore } from '../systems/GameStore';

const MAX_VISIBLE_DROPS = 8;
export class HomeScene {
  root = document.createElement('section'); private canvas=document.createElement('canvas'); private context=this.canvas.getContext('2d')!;
  private rockRenderer=new RockRenderer(); private drops:DroppedItem[]=[]; private particles:Particle[]=[]; private audio:AudioEngine;
  private last=performance.now(); private frame=0; private shake=0; private impact={x:0,y:0,life:0}; private rockOffset={x:0,y:0};
  private breaking=0; private entering=0; private transitionLocked=false; private resizeObserver?:ResizeObserver; private displayedHp=1;
  private timers=new Set<number>(); private changed=()=>{this.renderHud();this.syncDrops(true)}; private visibility=()=>{if(!document.hidden){this.last=performance.now();this.frame=requestAnimationFrame(t=>this.loop(t));}else cancelAnimationFrame(this.frame)};
  private noticeQueue:Array<{glyph:string;name:string}>=[]; private showingNotice=false;

  constructor(private store:GameStore, audio?:AudioEngine){this.audio=audio??new AudioEngine();this.root.className='scene home-scene';this.root.innerHTML=`<header class="scene-header"><div><span class="eyebrow">FIELD SITE 01</span><h1>赤土の採掘場</h1></div><div class="currency"><span>調査資金</span><strong data-coins></strong></div></header><button class="next-goal" data-goal type="button"></button><div class="progress-card"><div><span data-rock-subtitle></span><strong data-rock-name></strong></div><span data-rock-count></span></div><div class="mine-stage"><div class="hp-panel"><div class="hp-label"><b>岩の耐久度</b><span data-hp></span></div><div class="hp-track"><i data-hpbar></i><em data-hitbar></em></div></div><div class="drop-layer" aria-label="未回収の発見物"></div><div class="drop-hint">発見物をタップして標本箱へ</div><button class="mine-button" type="button"><span class="hammer-art" aria-hidden="true">▰</span><span><b>岩を叩く</b><small data-power></small></span></button></div><div class="toast" role="status"></div><div class="discovery" aria-live="polite"><span>NEW DISCOVERY</span><div data-discovery-glyph></div><b data-discovery-name></b><small>コレクションに登録しました</small></div>`;
    this.root.querySelector('.mine-stage')!.prepend(this.canvas);this.root.querySelector('.mine-button')!.addEventListener('click',()=>this.hitRock(this.canvas.clientWidth/2,this.canvas.clientHeight*.4));this.root.querySelector('[data-goal]')!.addEventListener('click',()=>this.quickUpgrade());this.canvas.addEventListener('pointerdown',e=>this.pointer(e));
    this.resizeObserver=new ResizeObserver(()=>{this.size();this.layoutRestoredDrops()});this.resizeObserver.observe(this.canvas.parentElement!);this.store.addEventListener('changed',this.changed);document.addEventListener('visibilitychange',this.visibility);this.audio.enabled=this.store.state.settings.sound;if(this.store.state.rockHp<=0)this.store.advanceRock();this.displayedHp=this.store.state.rockHp;this.syncDrops(true);this.renderHud();this.size();this.frame=requestAnimationFrame(t=>this.loop(t));}
  destroy(){cancelAnimationFrame(this.frame);this.resizeObserver?.disconnect();this.store.removeEventListener('changed',this.changed);document.removeEventListener('visibilitychange',this.visibility);this.timers.forEach(clearTimeout);this.timers.clear();}
  private later(fn:()=>void,ms:number){const id=window.setTimeout(()=>{this.timers.delete(id);fn()},ms);this.timers.add(id);}
  private size(){const box=this.canvas.parentElement!.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,3);this.canvas.width=Math.round(box.width*dpr);this.canvas.height=Math.round(box.height*dpr);this.canvas.style.width=`${box.width}px`;this.canvas.style.height=`${box.height}px`;this.context.setTransform(dpr,0,0,dpr,0,0)}
  private hitRock(x:number,y:number){if(this.transitionLocked)return;const result=this.store.hit();if(!result.damage)return;const cx=this.canvas.clientWidth/2,cy=this.canvas.clientHeight*.4,dx=Math.max(-1,Math.min(1,(x-cx)/100)),dy=Math.max(-1,Math.min(1,(y-cy)/100));this.rockOffset={x:dx*4,y:3+dy*2};this.impact={x:cx+dx*75,y:cy+dy*55,life:.11};this.shake=result.broken?7:3;this.particles.push(...impactParticles(this.impact.x,this.impact.y,this.store.rock.color,result.broken?2:.75));this.audio.hit(result.damage);if(this.store.state.settings.haptics)navigator.vibrate?.(result.broken?[25,30,32]:10);this.syncDrops(false);if(result.broken)this.breakRock()}
  private breakRock(){this.transitionLocked=true;this.audio.breakRock();this.later(()=>{this.breaking=.01;this.particles.push(...impactParticles(this.canvas.clientWidth/2,this.canvas.clientHeight*.55,'#786451',2.6))},40);this.later(()=>{this.store.advanceRock();this.breaking=0;this.entering=.01;this.transitionLocked=false;this.displayedHp=this.store.state.rockHp;this.renderHud()},540)}
  private syncDrops(restored:boolean){const visibleIds=new Set(this.drops.map(d=>d.dropId));this.drops=this.drops.filter(d=>this.store.state.pendingDrops.some(p=>p.dropId===d.dropId));for(const pending of this.store.state.pendingDrops){if(this.drops.length>=MAX_VISIBLE_DROPS)break;if(visibleIds.has(pending.dropId))continue;const item=itemById(pending.itemId);if(!item)continue;const index=this.drops.length,direction=index%2?-1:1;const drop=new DroppedItem(pending.dropId,item,this.canvas.clientWidth/2+direction*8,this.canvas.clientHeight*(restored?.66:.36),direction,restored);this.drops.push(drop)}this.renderDropButtons()}
  private layoutRestoredDrops(){const ground=this.canvas.clientHeight*.72;this.drops.filter(d=>d.settled).forEach((d,i)=>{d.x=38+(i%4)*(Math.max(76,(this.canvas.clientWidth-76)/3));d.y=ground-d.radius});this.renderDropButtons()}
  private pointer(e:PointerEvent){const b=this.canvas.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;for(let i=this.drops.length-1;i>=0;i--)if(this.drops[i]!.hit(x,y)){this.collect(this.drops[i]!);return}if(Math.hypot(x-this.canvas.clientWidth/2,y-this.canvas.clientHeight*.4)<125)this.hitRock(x,y)}
  private collect(drop:DroppedItem){const result=this.store.collectDrop(drop.dropId);if(!result)return;this.drops=this.drops.filter(d=>d.dropId!==drop.dropId);this.audio.collect();this.showToast(`${drop.item.name}　+1`);const fly=document.createElement('span');fly.className='collect-fly';fly.textContent=drop.item.glyph;fly.style.left=`${drop.x}px`;fly.style.top=`${drop.y}px`;fly.style.setProperty('--item',drop.item.color);this.root.append(fly);this.later(()=>fly.remove(),460);if(result.firstDiscovery){this.audio.discover();this.noticeQueue.push({glyph:drop.item.glyph,name:drop.item.name});this.showNextNotice()}this.syncDrops(true)}
  private renderDropButtons(){const layer=this.root.querySelector('.drop-layer')!;layer.replaceChildren(...this.drops.map(drop=>{const b=document.createElement('button');b.type='button';b.dataset.drop=drop.dropId;b.setAttribute('aria-label',`${drop.item.name}を回収`);b.style.left=`${drop.x-28}px`;b.style.top=`${drop.y-28}px`;b.addEventListener('click',()=>this.collect(drop));return b}))}
  private showNextNotice(){if(this.showingNotice||!this.noticeQueue.length)return;this.showingNotice=true;const n=this.noticeQueue.shift()!,panel=this.root.querySelector('.discovery')!;this.set('[data-discovery-glyph]',n.glyph);this.set('[data-discovery-name]',n.name);panel.classList.add('show');this.later(()=>{panel.classList.remove('show');this.showingNotice=false;this.showNextNotice()},this.store.state.settings.reducedMotion?1800:1150)}
  private showToast(t:string){const e=this.root.querySelector('.toast')!;e.textContent=t;e.classList.remove('show');void (e as HTMLElement).offsetWidth;e.classList.add('show')}
  private quickUpgrade(){const u=UPGRADES[0]!,cost=upgradeCost(u,this.store.state.upgrades.hammer);if(this.store.state.coins>=cost)this.store.buy('hammer')}
  private renderHud(){const s=this.store.state,r=this.store.rock;this.audio.enabled=s.settings.sound;this.set('[data-coins]',`${s.coins} c`);this.set('[data-rock-name]',r.name);this.set('[data-rock-subtitle]',r.subtitle);this.set('[data-rock-count]',`${s.rocksBroken} 岩石を調査済み`);this.set('[data-hp]',`${s.rockHp} / ${r.maxHp}`);this.set('[data-power]',`採掘力 ${this.store.damage}`);const goal=this.root.querySelector<HTMLButtonElement>('[data-goal]')!,cost=upgradeCost(UPGRADES[0]!,s.upgrades.hammer);if(s.coins>=cost){goal.textContent=`強化可能：地質ハンマーを ${cost} c で強化`;goal.disabled=false}else if(s.onboarding.eligible&&!s.onboarding.guaranteedIron){goal.textContent='次の目標：岩を2回叩いて地層を調べる';goal.disabled=true}else if(s.pendingDrops.length){goal.textContent=`次の目標：発見物を回収する（${s.pendingDrops.length}個）`;goal.disabled=true}else{goal.textContent='次の目標：岩を砕いて調査資金を得る';goal.disabled=true}}
  private set(q:string,t:string){const e=this.root.querySelector(q);if(e)e.textContent=t}
  private loop(now:number){const dt=Math.min((now-this.last)/1000,.034);this.last=now;this.draw(dt);if(!document.hidden)this.frame=requestAnimationFrame(t=>this.loop(t))}
  private draw(dt:number){const c=this.context,w=this.canvas.clientWidth,h=this.canvas.clientHeight,ground=h*.72;c.clearRect(0,0,w,h);c.save();if(this.shake>0&&!this.store.state.settings.reducedMotion){c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);this.shake=Math.max(0,this.shake-38*dt)}c.fillStyle='#272018';c.fillRect(0,ground,w,h-ground);c.fillStyle='#50402e';c.fillRect(0,ground, w,4);this.displayedHp+=(this.store.state.rockHp-this.displayedHp)*Math.min(1,dt*10);const ratio=Math.max(0,this.displayedHp/this.store.rock.maxHp);if(this.breaking>0)this.breaking=Math.min(1,this.breaking+dt*2.8);if(this.entering>0){this.entering=Math.min(1,this.entering+dt*2.2);if(this.entering===1)this.entering=0}this.rockRenderer.draw(c,this.store.rock,{x:w/2+this.rockOffset.x,y:h*.4+this.rockOffset.y,impactX:this.impact.x,impactY:this.impact.y,damageRatio:ratio,breaking:this.breaking,entering:this.entering});this.rockOffset.x*=Math.max(0,1-dt*22);this.rockOffset.y*=Math.max(0,1-dt*22);this.drawImpact(c,dt);this.drops.forEach(d=>{d.update(dt,ground,w);c.save();c.translate(d.x,d.y);c.rotate(d.rotation);c.shadowColor='rgba(0,0,0,.5)';c.shadowBlur=7;c.shadowOffsetY=4;drawItem(c,d.item);c.restore()});this.renderDropButtons();this.particles=updateParticles(this.particles,dt);this.particles.forEach(p=>{c.globalAlpha=Math.min(1,p.life/p.maxLife);c.fillStyle=p.color;if(p.kind==='dust'){c.beginPath();c.arc(p.x,p.y,p.size,0,Math.PI*2);c.fill()}else c.fillRect(p.x,p.y,p.size,p.size)});c.restore();const hp=this.root.querySelector<HTMLElement>('[data-hpbar]'),hit=this.root.querySelector<HTMLElement>('[data-hitbar]');if(hp)hp.style.width=`${ratio*100}%`;if(hit)hit.style.width=`${Math.max(ratio,this.store.state.rockHp/this.store.rock.maxHp)*100}%`}
  private drawImpact(c:CanvasRenderingContext2D,dt:number){if(this.impact.life<=0)return;this.impact.life-=dt;c.save();c.translate(this.impact.x,this.impact.y);c.strokeStyle=`rgba(244,225,185,${Math.max(0,this.impact.life*7)})`;c.lineWidth=3;for(let i=0;i<4;i++){c.rotate(Math.PI/2);c.beginPath();c.moveTo(8,0);c.lineTo(18,0);c.stroke()}c.restore()}
}
